FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \ 
    apt-get upgrade -y && \
    apt-get install -y \ 
    apache2 libxml2-dev

RUN a2enmod proxy && \
    a2enmod proxy_ajp && \
    a2enmod proxy_http && \
    a2enmod rewrite && \
    a2enmod deflate && \
    a2enmod headers && \
    a2enmod proxy_balancer && \
    a2enmod proxy_connect && \
    a2enmod proxy_html

WORKDIR /var/www/html

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]